### ISSUE TITLE
This repository!

### ISSUE THREAD

**Issue by adunkman** [NodeDC/organizers#1]
I was just sending some email on behalf of Node.DC, and thought to myself, ”This might be something that would be good to have a record of.” 

Yesterday evening, while preparing an email for a Call for Proposals release (#2), I referenced back to my old email from December — and that would be a nice thing to do, regardless of who will be organizing the group in 6 months, a year, whathaveyou. 

So, I’m going to try to publish most of the correspondence and decision making stuff things whatever here. It could work out, or we could delete the repository in 2 weeks and call it a failure. But it doesn’t hurt to try!

**Comment by jonathana** [comment]
Please do try,  I like the idea.

**Comment by adunkman** [comment]
Yeah! Here we goooooo!!

![image](https://cloud.githubusercontent.com/assets/14930/7088858/48de833e-df65-11e4-9313-95ecb4d1d2ee.png)

**Comment by danmactough** [comment]
👍

**Comment by mcwhittemore** [comment]
I love this idea! Emails and meetings always stressed me out but a comment on a github issues is like pie!
