### ISSUE TITLE
Regular Weekend NodeSchools?

### ISSUE THREAD

**Issue by joshfinnie** [NodeDC/organizers#17]
Thinking about how to better serve the NodeSchool community, and was wondering if we should have a regular weekend thing very much like DCPython does with [their labs](http://www.meetup.com/DCPython/events/221383110/). Thoughts?

**Comment by danmactough** [comment]
I can't do weekends, but this is a nice idea (except for people who can't do weekends).

**Comment by JuanCaicedo** [comment]
I like the idea! Personally though, I go to Nova Code Coffee every other Saturday and I don't think I'd go to two events like that in one weekend. I would definitely swing by NodeSchool here and then though.

**Comment by adunkman** [comment]
I probably wouldn’t show up, because weekends — but I wouldn’t poo-poo other people from doing it. :)

**Comment by mcwhittemore** [comment]
I know MLK library does Python things too, might be something to see if they were interested in.

**Comment by robbiethegeek** [comment]
Thanks @adunkman for summoning me into this.  I am game to be a part of anything that gets going for NodeSchool for sure.  I would love to see the Nova Code and Coffee (NCC) and NodeSchool (NS)not compete, maybe we can do 1 weekend NS (3-4 hours) on a non-NCC weekend and one weeknight NS (2-3 hours) a month.  So that we can service both types of attendees, those that are anti-weekend events  and those that can only attend things on weekends.

**Comment by JuanCaicedo** [comment]
Nova Code & Coffee is on a regular schedule, so they're easy to plan around (it's been every two weeks for the last year, with only one exception). 

The two per month seems like a good plan @robbiethegeek! My only thought is that the weekday ones  have been hard to schedule (both Nova Node and NodeDC have been having lots of events). If you want to take the lead on finding a day you think is best, we'll all help make it happen and arrange a space.

**Comment by robbiethegeek** [comment]
Will do @JuanCaicedo thanks all for welcoming me to the Node communities here in DC/VA and bringing me into the organizers conversation!

**Comment by robbiethegeek** [comment]
Looks to me like 1st Wednesday of the month is open on both calendars.  So the next 3 events would be 6/3, then 7/1, than 8/5. Lets take a quick vote?  Is this acceptable? If so is there a venue close to the metro we can get a commitment for these events?

**Comment by danmactough** [comment]
I just updated the calendar: June 1 is the talk with Lin Clark #18, so I removed the pending Node Night on June 4. Sorry for the confusion, @robbiethegeek -- obviously, June 3 won't work. :smile:

**Comment by robbiethegeek** [comment]
June aside I did a comparison of the 2 groups meetup calendars back to January and seems like the first week of the month is pretty clean.  I think we can skip June and maybe make announcements for July onward if that is great way to build buzz and chat with possible mentors at June's meetups / unconference (even maybe have a session for mentors at the Unconference to talk about nodeschool, what it is, what mentors do, how to be prepared).

**Comment by JuanCaicedo** [comment]
Those sound good to me, let's get 7/1 on the calendar! I think something at the unconf is a good idea, since I know that a few of the attendees coming are going to have never done Node before. What we could do is plan to have an hour or two of node school at some point and then schedule any non-newbie-friendly topics during that same block. I love the idea of a node school mentor session too, I'm sure that'll get a bunch of votes!

**Comment by JuanCaicedo** [comment]
@joshfinnie Is all about the Nodeschools, so maybe at Track Maven? Uber Offices is usually good about having us, but it might require more coordinating and they might not be able to do it everytime. 

Of course, if you don't mind coming to Rosslyn, Fluencia is almost always available!

**Comment by robbiethegeek** [comment]
I'm coming from Braddock, and new to the area but as long as it is on the metro, I think we are good.  Thanks for all the feedback and input, can't wait to get this going.

**Comment by robbiethegeek** [comment]
Started a google doc that is a proposal for what to cover at the Unconference and start talking through some ideas I have for what we should be supporting / doing at each event.
https://docs.google.com/document/d/1NX96J4enDmUCwsdEvkY-agyNftzB0M_L1XqRywQbPIY/edit?usp=sharing

**Comment by danpaz** [comment]
Added some comments to the doc. Looks good @robbiethegeek!

**Comment by JuanCaicedo** [comment]
@robbiethegeek I officially added Nodeschool to the unconf schedule! Should we put anything together ahead of time?

**Comment by joshfinnie** [comment]
@JuanCaicedo I will probably be attending the unconference if you want help with NodeSchool...

**Comment by joshfinnie** [comment]
Also, if we are a go with having a NodeSchool session... maybe it is time to put the [NodeSchool/WashingtonDC](https://github.com/nodeschool/washingtondc) repo to good use...

**Comment by JuanCaicedo** [comment]
@joshfinnie That would be great! If you and @robbiethegeek are both down, we'll have you guys be the two in charge. I'll email you both to get it all figured out.

For the repo, I assume you mean listing something about the regular NodeSchools, not the unconf?

@robbiethegeek In the updated schedule (#3) that @adunkman proposed, there's quite a few node nights, including one on 7/2. How would you feel about planning the weekend NodeSchool on the off weeks of that (e.g. 7/11 and 8/8? Also, would you still want a weekday NodeSchool, or could we get all our newbies to just come to NodeNight?

**Comment by robbiethegeek** [comment]
@JuanCaicedo I like the weekend events dates those are good with me, I am concerned that we will not get mentors if we have an ongoing meetup happening, and I wouldn't want to take over the meetup completely if there are intermediate and advanced devs that don't want to participate in NodeSchool.  Maybe we can start off with weekend only events and then branch out from there thoughts especially @joshfinnie .

**Comment by robbiethegeek** [comment]
Hey folks wanted to bring up NodeSchool weekend events again since tomorrow night is the node night and I won't be there, I still think that a Saturday NodeSchool would be a great addition to the NovaNode DC Node events.

**Comment by robbiethegeek** [comment]
7/11 is still open for me.

**Comment by JuanCaicedo** [comment]
I'm going to be out of town on the 11th, and it's also the same weekend as Nova Code & Coffee. What would you think about the 18th? 

Also, since no one has mentioned a location, let's do it at Fluencia

**Comment by robbiethegeek** [comment]
I can't do 7/18 my mother-in-law is visiting :) First person to stay at our place since we moved here.  7/25?

**Comment by danpaz** [comment]
7/25 is Nodebots!

**Comment by robbiethegeek** [comment]
Do you think there is a lot of crossover from NOVA Code & Coffee over at Custom Ink and NodeSchool?  Also can we move this conversation out of this issue and into gitter.im https://gitter.im/nodeschool/washingtondc

**Comment by JuanCaicedo** [comment]
I don't think a huge amount, but there is me...

**Comment by JuanCaicedo** [comment]
@danmactough Do you know what's going on with [the nodeschool repo](https://github.com/NodeDC/nodeschool.github.io)? I was looking to start fork off the main one, but then it turned out there already is one.

**Comment by danmactough** [comment]
@JuanCaicedo I just submitted a little clean-up to them. You can update the fork or delete it and fork it again.

**Comment by robbiethegeek** [comment]
Hey folks there was talk this past weekend at NodeBots day of kicking off the regular NodeSchools this Saturday...it is getting pretty late to have folks clear their schedules, and commit to a full day of tech stuff.  I am still game to be the lead, just need to get the event created and then generate some buzz.

**Comment by JuanCaicedo** [comment]
@robbiethegeek I'll make it and I'll see if we can add you as an admin for you to make events in the future

**Comment by robbiethegeek** [comment]
Thanks @JuanCaicedo !

**Comment by robbiethegeek** [comment]
Also I spun up a twitter accout https://twitter.com/NodeSchoolDC and a gmail account to signup that twitter account nodeschooldc@gmail.com

**Comment by JuanCaicedo** [comment]
Awesome! So the only thing left is making a follow up to Dan's PR to nodeschool.github.io, which I can do

**Comment by adunkman** [comment]
(Closing because this seems no longer relevant, re-open if you disagree!)

**Comment by danpaz** [comment]
@danmactough We (@robbiethegeek and I) are going to try to get the dc chapter up on nodeschool.io, looks like the easiest way to get that done is to delete the existing fork and fork it again, and make a pr to add our chapters json and a link on the chapters page to https://github.com/nodeschool/washingtondc.

**Comment by danmactough** [comment]
Cool. Thanks for the heads up. Need anything from me?

**Comment by joshfinnie** [comment]
@danpaz what do you want with the washingtondc nodeschool.io branch? I have full control over it. I think I can add people. Let me know.

I have been thinking of getting it added to the website, shouldn't be too hard.

**Comment by danpaz** [comment]
@joshfinnie for the washingtondc repo our plan today is to
- add links to the meetup pages (nodedc and novanode)
- update the social media stuff
- add a list of mentors

Eventually I think we'd like to make a gh pages page (e.g. check out the [baltimore page](http://nodeschool.io/baltimore/)!)

**Comment by danpaz** [comment]
Adding washingtondc to the nodeschool.io website https://github.com/nodeschool/nodeschool.github.io/pull/405
