### ISSUE TITLE
NPM talk June 1

### ISSUE THREAD

**Issue by danmactough** [NodeDC/organizers#18]
@linclark from NPM will be in town on June 1 and would like to hang out and/or give a talk.  Let's do something!

**Comment by JuanCaicedo** [comment]
Sounds fun! What would we need to figure out to put it together? Just a space?

**Comment by linclark** [comment]
Thanks for getting the ball rolling on this. I'd be happy to give a talk, so a space with a projector would be great.

**Comment by danmactough** [comment]
@linclark Would an afternoon "Lunch & Learn" style meetup work? We (@socialtables) can host!

**Comment by linclark** [comment]
Unfortunately I can't make it until the evening.

**Comment by danmactough** [comment]
Ok. No problem.

**Comment by danpaz** [comment]
This is really exciting!

**Comment by danmactough** [comment]
I've created (but not announced) a [meetup](http://www.meetup.com/node-dc/events/222494625/) and emailed UberOffices to see if they're available. @linclark If you have a title and writeup for the talk, please plunk it here or feel free to email me (same username at gmail).

**Comment by JuanCaicedo** [comment]
@danmactough It's always nice to have events at UberOffices! If they can't for any reason, we'd be happy to have everyone here at Fluencia again, though we wouldn't be able to provide food and bevs like we do for Node Nights. Let us know when they get back to you!

**Comment by danmactough** [comment]
We have a venue for June 1, so we are on! :tada: @linclark Please let me know what you want to present, and I'll update the meetup announcement and announce it.

**Comment by adunkman** [comment]
Woohoo! :)

**Comment by linclark** [comment]
Great!

Depending on what you think the audience would be interested in, I could give one of two talks:
- **The Evolution of Modularity**—I gave this one at NodeDay in NYC a few weeks back. It covers the major landmarks in the history of modularity and how that's shaped our concept of modularity today. This is a high level talk.
- **Babel: How to live in the future without abandoning today's users**—Will be giving this one at jQuerySF in a few weeks. It will cover how to use Babel to work with ES6 today. It's more demonstration heavy.

**Comment by danmactough** [comment]
Two great talks! We just had a talk nearly identical to your Babel talk, so let's do "The Evolution of Modularity". I will update the meetup and announce it. Let me know if you have any questions, logistical or otherwise.
