### ISSUE TITLE
7/2 Node Night

### ISSUE THREAD

**Issue by JuanCaicedo** [NodeDC/organizers#19]
Following the conversation from #3, we can host at Fluencia and NovaNode!

Do we want to handle RSVPs the same way as last time (Host an event with no RSVP on NodeDC with a link to NovaNode, and accept RSVPs there)?

**Comment by joshfinnie** [comment]
@JuanCaicedo sounds good to me... let me know when you post on NovaNode and I will copy it on NodeDC!

**Comment by JuanCaicedo** [comment]
@adunkman @danmactough 

Sadly, @danpaz is going to be out of town

**Comment by adunkman** [comment]
> Sadly, @danpaz is going to be out of town

:sob:

**Comment by danpaz** [comment]
Sad but true! I'll be back for Nodebots though :smile:

**Comment by jkeam** [comment]
:+1:

**Comment by JuanCaicedo** [comment]
@joshfinnie Event is up! http://www.meetup.com/Nova-Node/events/223377810/

@joshfinnie @adunkman I added both of you as hosts, so you should be able to edit the event. @danmactough if you're planning on going, I can throw you up there too.

**Comment by adunkman** [comment]
:heart:
