### ISSUE TITLE
Spring Call for Proposals

### ISSUE THREAD

**Issue by adunkman** [NodeDC/organizers#2]
Back in December we released a Call for Proposals, which was a new thing for us. We were struggling to get monthly presentations going because of a chicken-and-the-egg problem — we needed a space to confirm a date, and a speaker wouldn’t commit to presenting unless they had a date, but we didn’t want to book spaces without knowing that we could have a speaker. 

So, we tried a new approach — asking speakers to prepare their thoughts for a presentation and submit them to us. The benefit here is that we’d have hard subject matter and a number of speakers — so we felt comfortable booking a space, knowing that it was pretty likely that at least one of the speakers would be available to present on that date. 

Woohoo! Great success. We’ve been using those submissions from December up through last night’s meetup. 

We still have additional talks that haven’t been heard, but I’m losing my confidence that the speakers we have are (a) still interested in presenting on the subjects they submitted back in December and (b) still available to present. A lot happens in 5 months!

So, I’m going to open a new Call for Proposals today, to get new ideas and to validate that the speakers who haven’t yet spoken are still interested.

**Comment by adunkman** [comment]
Just sent out an email to speakers who haven’t presented from the last Call for Proposals: 

> #### Node.DC: Please consider resubmitting your presentation!
> 
> Good morning! 
> 
> Node.DC is about to open another Call for Proposals for the next few months of talks. As someone who submitted to Node.DC’s last Call for Proposals but your talk wasn’t selected, we’d like to encourage you to consider reviewing and potentially resubmitting your talk, if you’re still interested in the subject.
> 
> There are a number of reasons for talks not being selected — we focus on maintaining even spacing between talks, varying subject matter and technical content, and a mix of fresh and new technology with deep dives. Just because your talk wasn’t selected doesn’t mean we don’t want to hear about it!
> 
> “So why are you making me submit again?” I hear you! As mentioned in last night’s meetup, JavaScript changes very quickly, and we want to make sure that you’re still interested and passionate about the subject you submitted. Passionate presenters lead to great debate! 
> 
> Thanks for considering resubmitting, and have a wonderful weekend! 
> 
> Andrew

**Comment by adunkman** [comment]
About to send the announcement to the meetup group:

> #### Spring Call for Proposals
> 
> Hello Friends! 
> 
> Spring is here! With the coming of spring we’re opening a Call for Proposals. We’ll use the content that you submit to plan the next few months of meetups.
> 
> If you’re not familiar with the concept of a Call for Proposals, we’re just formally asking you to spend a few moments to consider if you’d like to share content with Node.DC through a presentation or workshop.
> 
> We’re opening the Call for Proposals today, and it will remain open through April 25th — ten days after you finish your taxes! Send any questions to Andrew (adunkman@gmail.com) or shoot us a tweet @NodeDC.
> 
> Call for Proposals: http://bit.ly/1cfK7jz.
> 
> Thank you for considering sharing your knowledge! 
> Andrew

**Comment by adunkman** [comment]
Regarding the form, the questions are the same as last time (they yielded pretty good results) with one exemption: 

> #### Call for Proposals: Node.DC — Spring 2015
> 
> Spring is here! With the coming of spring we’re opening a Call for Proposals. We’ll use the content that you submit to plan the next few months of meetups.
> 
> Thank you for considering sharing your knowledge with the Node.DC community!
> 
> Ideally, your content will take between 45 minutes and an hour to share. If that format doesn’t work well for your idea, submit it anyways, and let us know in the description! Great ideas bend the rules when appropriate. :)
> 
> ##### Name *
> 
> We’d like to call you by the correct name — if your submission is accepted, this is how we’ll refer to you.
> [ textbox ]
> 
> ##### Email Address *
> 
> We’ll contact you after the Call for Proposals ends to let you know the status of your submission.
> [ textbox ]
> 
> ##### Title *
> 
> A short, descriptive title for your content. Try to avoid being too clever.
> [ textbox ]
> 
> ##### Abstract *
> 
> A few sentences describing your content. A good abstract describes not only what you’re going to cover, but also how you hope your audience will change after hearing your content.
> [ textarea ]
> 
> ##### JavaScript outside of the browser
> 
> We’re currently focusing on presenting content that centers around JavaScript running outside of web browsers.
> - [ ] Browser-based: My content is centered around JavaScript executing in a web browser.
> - [ ] Not browser-based: My content is centered around JavaScript executing outside of a web browser.
> 
> ##### Will you be present in Washington, DC?
> 
> We are open to receiving presentations remotely, if you are unable to be present with us in Washington, DC.
> - [ ] I will be in Washington, DC while presenting.
> - [ ] I will be presenting remotely.
> 
> ##### Prerequisites
> 
> What do you expect someone to know to understand your content?
> [ textarea ]
> 
> ##### Additional Information
> 
> Is there anything else you think we should know about?
> [ textarea ]
> 
> ##### Code of Conduct *
> 
> The Node.DC community is made up of a mixture of professionals and volunteers with different levels of understanding and personal beliefs. This diversity is one of our strengths, and in an effort to enrich and protect our community we’ve enacted a Code of Conduct that can be read online at https://github.com/NodeDC/CodeOfConduct.
> - [ ] I have read, understand, and agree to follow the Node.DC Code of Conduct.

I removed this field: 

> ##### Reaching Out
> 
> Are there specific people or organizations that you think would benefit from hearing your content?
> [ textarea ]

Most people left this blank, and we didn’t do anything with the results. No sense in making people fill something out that we’re ignoring.

**Comment by adunkman** [comment]
Oh! One more thing I just arbitrarily decided — the CFP end-date. I picked April 25th. 

Back in December, we had it open for 10 days — December 11th through the 21st. The reason for this was that we didn’t think of doing it before December 11th, and we wanted to be able to review the submissions before we went on vacations (although, that didn’t actually happen, so ¯\_(ツ)_/¯). The length of time was pretty good though, I think. People had enough time to think about it, but not enough time to procrastinate forever. 

We’re asking people to write a title and a paragraph, after all.

This time around, I wanted to pick a date that would be easy to remember, and not fall on a weekend. As someone who fills out a lot of CFPs, I always kid myself into thinking that if a CFP closes on the weekend, I’ll have time to work on it on the weekend — but then the weekend rolls around and I rediscover what it feels like to breathe fresh air, and I miss it.

April 15th is generally easy to remember because of tax day, but too soon — so the 25th it is!

**Comment by adunkman** [comment]
Hahahahaha I’m such a joke! Just realized the 25th is a Saturday. Oh well! 

![helpless!](https://33.media.tumblr.com/3706fa06d24015c22a2dc97981f5b897/tumblr_n8iko9sZCf1sbo963o1_r2_500.gif)

**Comment by adunkman** [comment]
Just announced via Meetup and Twitter — [bit.ly analytics](http://bit.ly/1cfK7jz+).

Scheduled tweets for:
- Sunday, April 12th at 7:30am
- Wednesday, April 15th at 11:00am
- Friday, April 17th at 2:00pm
- Tuesday, April 21st at 5:30pm
- Friday, April 24th at 12:00pm
- Saturday, April 25th at 9:30am

**Comment by mcwhittemore** [comment]
+1

**Comment by mcwhittemore** [comment]
Also, we just moved my weekly Thursday meeting to start at 4 rather than 7 so I might start showing up again!

**Comment by adunkman** [comment]
Closed the CFP form with this message: 

> Thank you for your great submissions! We’re now combing over the proposals and will be in touch shortly.
> 
> If you’re a procrastinator and have missed the deadline, we might be able to make an exception for you — get in touch with the organizers through our Meetup group: http://www.meetup.com/node-dc.

We received 8 responses. No previous submitters submitted talks to this round. 

I’ll be closing this issue, and we can continue discussion of reviewing the submissions on #3!

**Comment by danmactough** [comment]
@adunkman This roadmap was super-helpful. Thank you!! :cake:

**Comment by adunkman** [comment]
Woohooo!! :D :tada:
