### ISSUE TITLE
8/19 NodeSchool with TechTalkDC

### ISSUE THREAD

**Issue by JuanCaicedo** [NodeDC/organizers#20]
@joshfinnie @robbiethegeek @adunkman @danpaz 

@duluca reached out to me about doing a joint NodeSchool between TechTalkDC, NovaNode and NodeDC. The plan would be to do a 3 hour format, 5:30-8:30 on Wednesday 8/19, I'm assuming at Excella HQ near the Courthouse Metro. It could be a more self guided plus mentors event like we usually do, or perhaps something more directed. 

I think I might be out of town around then, but if you guys are all into it, let's make it happen!

**Comment by robbiethegeek** [comment]
I am in!  Sounds great!  We can start cross promoting once we have it locked in.

**Comment by joshfinnie** [comment]
Yeah, that sounds awesome! Let's do it :+1:

**Comment by joshfinnie** [comment]
@robbiethegeek this reminds me, you a member of this repo? https://github.com/nodeschool/washingtondc

**Comment by robbiethegeek** [comment]
@joshfinnie yup looks like I am :)

**Comment by duluca** [comment]
i'd love to become a member, we were having some interesting discussions with @maxogden during NodeConf. We have plans to contribute a workshopper over the next few months. @JuanCaicedo we can publish a list of recommended tracks of workshoppers for beginners, intermediate and advanced folks. There definitely was talk of potentially structuring NodeSchool.io in a similar manner. I'll create the Meetup event and report back here.

**Comment by duluca** [comment]
http://www.meetup.com/TechTalkDC/events/223342016/

**Comment by JuanCaicedo** [comment]
The meetup is announced now as well as an event in both Nova Node and NodeDC linking people there!

**Comment by joshfinnie** [comment]
@JuanCaicedo you might want to turn off the waitlist function. Otherwise :+1:

**Comment by duluca** [comment]
Already sold out, have a wait list of 7! So far so good :)

**Comment by joshfinnie** [comment]
@duluca did you bump up the limit? Saw there's 7 spots available...

**Comment by joshfinnie** [comment]
Also, have any idea on how many mentors we'll be having tomorrow?

**Comment by danpaz** [comment]
I'll be there and happy to mentor

**Comment by joshfinnie** [comment]
:+1: me too, but with 80 people, we'd hope for 8+ just wondering if @duluca had an estimation. :-)

**Comment by robbiethegeek** [comment]
I will be there hopefully at 6pm :)

And am happily a mentor!

**Comment by duluca** [comment]
@danpaz it'd be great to have you as a mentor. And with you I think we would at least have 6 mentors and I'm asking 2 other people. @joshfinnie yes I bumped up the list. Technically we have space for a hundred and our attendance rate have always hovered around 50% of RSVPs. Bit of a gamble on my part to increase overall attendance, but even if 80 shows up we should be fine.

**Comment by JuanCaicedo** [comment]
If I don't get a package today that I need to go to Montreal, I'll be there to help mentor too!

**Comment by joshfinnie** [comment]
Thanks to all who participated in this! It was great.
