### ISSUE TITLE
Summer 2015 - Submission HTTP2/Push

### ISSUE THREAD

**Issue by rektide** [NodeDC/organizers#21]
# Http2/Push Inside the Firewall (And Out)
## Abstract

HTTP is the well known transport-protocol that makes up the world wide web, but it also works extra-hard inside the firewall at many companies as a means to let services communicate with one another. With the recent ratification of HTTP2, RFC7540, this May, HTTP has gained a series of new features that make it even more attractive as the means to send data around, inside the firewall and out.

Thankfully, Node Wunderkind @indutny has been working diligently to give us Node data-pushers a cutting edge, yet friendly and not-too-dissimilar means to use and enjoy this new persistently-connected rendition of HTTP2! We'll start out going through his node-spdy and spdy-transport projects to see how things get better when we change require('http') to require('spdy').

From there, we'll look at a sample "inside the firewall" application built as microservices, pushing data between the components over persistent TCP/HTTP2 connections using HTTP2/Push, one of the newest most radically different capabilities introduced in HTTP2.

It should be a very informative night for people of all levels. At the end, we'll also launch the application: a new social tool to help DC JS'ers stay in touch and sharing company more often.
## JavaScript outside of the browser

Yes! Yes yes yes! Also some UI in the browser too, but small.
## Present in DC

Yes, in the District!
## Prerequisites

This talk starts at a high level, with historical context of HTTP and HTTP2, which should be of general interest and use. From there, knowledge of `require("http").createServer()` would help, but shouldn't be a major block. The talk is very technical, but should be very welcoming!
## Code of Conduct

I have read, understand, and abide by the Node.DC Code of Conduct!

**Comment by rektide** [comment]
This talk might also be a good one to see if DCJS wants to cohost- Node, but so HTTP-centric that it should be interesting for their audience too. @adunkman? @elgreg?

**Comment by danmactough** [comment]
@rektide This talk sounds awesome.

I don't know about co-hosting. I'm not against it, but **most** of our talks should have a something that's interesting for DCJS's audience. Co-hosting requires a fair bit of administrative overhead -- meetup announcements, but only one can have RSVPs open. Blerg. I'd rather just cross-promote -- which we already do, just ... poorly.

**Comment by JuanCaicedo** [comment]
I feel the same as Dan. I would love to see this talk!

**Comment by elgreg** [comment]
DCJS is struggling under the load of all 3 members having kids (one 1st,
one 2nd and one 3rd) in the last 8 mos. Happy to cross promote but we're
still trying to get ourselves together to have an actual meetup in 2015. :)

I'd node.dc hosts we'll definitely assist with announcements!

**Comment by elgreg** [comment]
And by members w/kids I meant organizers. :)

**Comment by mcwhittemore** [comment]
+1

**Comment by danmactough** [comment]
@rektide You can go ahead at create a NodeDC meetup. I'll help you get the space.

**Comment by danmactough** [comment]
@rektide What I mean is, choose a date/time that works for you. :smile:

**Comment by danmactough** [comment]
@rektide and I discussed 10/15 for this.

**Comment by danmactough** [comment]
Scheduled and announced: http://www.meetup.com/node-dc/events/225468321/
