### ISSUE TITLE
NodeSchoolDC - September

### ISSUE THREAD

**Issue by robbiethegeek** [NodeDC/organizers#23]
I have created a new event on 9/12/15 - 
http://www.meetup.com/node-dc/events/224849713/

@JuanCaicedo / @danpaz since it is hosted at Fluencia I would like confirmation before putting it live.

**Comment by danpaz** [comment]
LGTM! Should we set the expectation here re: pairing?

**Comment by robbiethegeek** [comment]
Yes we should! I will update it to mention that :) :+1: 
After that I am going to push it live...

**Comment by robbiethegeek** [comment]
Updated and posted!
