### ISSUE TITLE
Node.js v4 talk Sept 24

### ISSUE THREAD

**Issue by danpaz** [NodeDC/organizers#24]
@cjihrig is offering to come down to give a talk on node v4. The JS calendar for September looks clear to me so I was thinking Sept 24, and if space is an issue we could probably host this one at Fluencia. Does that work for everyone? 

I think Colin would have to clear this with his work and the Node foundation so we won't announce until we've settled on all the details.

**Comment by danmactough** [comment]
Dang. I was just about to schedule something. That's great, though.

**Comment by danpaz** [comment]
We're a go. I'll create the event in NovaNode to be hosted at Fluencia, and I _think_ I have enough permission to create an event in NodeDC pointing people to NovaNode? If not I'll ping someone to help me out. Really excited for this!

**Comment by danpaz** [comment]
@danmactough @adunkman @robbiethegeek @JuanCaicedo @cjihrig

http://www.meetup.com/node-dc/events/225124602/
http://www.meetup.com/Nova-Node/events/225124520/

Let's get the tweet storm rolling.

**Comment by adunkman** [comment]
Scheduled a few tweets for nodedc! <3

**Comment by danpaz** [comment]
Is there such thing as scheduled retweets? That would be super useful!

**Comment by JuanCaicedo** [comment]
@danpaz I've heard of it through [TweetDeck](http://smallbusiness.chron.com/can-schedule-multiple-tweets-tweetdeck-32192.html)

**Comment by jonathana** [comment]
Will Buffer do it?
