### ISSUE TITLE
Flux in 27 doodles by Lin Clark

### ISSUE THREAD

**Issue by robbiethegeek** [NodeDC/organizers#25]
Hey folks,

I noticed that @linclark was speaking at Brooklyn JS and tweeted that I wish there was a video stream https://twitter.com/RobbieTheGeek/status/644184106927001601. Thanks for the response Lin, seems like she is willing to present next time she is in the area :)

Wanted to kickstart this,

Robbie

**Comment by JuanCaicedo** [comment]
That would be awesome! She was a pretty sweet speaker.

**Comment by linclark** [comment]
I'd be happy to give the talk when I'm down there next. Remind me, what day of the month is NodeDC usually on again?

**Comment by danmactough** [comment]
Usually Thursday, but we're flexible.

**Comment by robbiethegeek** [comment]
Hey @linclark was great running into you at Empire Node, was wondering if you happened to be heading to the area for the holidays and were available? :)

**Comment by linclark** [comment]
I'm not headed down there for the holidays, but I'll definitely be headed down sometime in spring. I'll be sure to let you know when that is :)

**Comment by robbiethegeek** [comment]
No problem have a happy holidays, look forward to seeing you in the spring :)
