### ISSUE TITLE
October 2015 NodeSchoolDC

### ISSUE THREAD

**Issue by robbiethegeek** [NodeDC/organizers#26]
Hey folks wanted to start the conversation / planning for October.

How does 10/10 look for you @danpaz / @JuanCaicedo for hosting at Fluencia?

I am heading to EmpireNode on 10/23 and will be out of town that weekend and 10/17 is 2 days after the DCNode meetup about http2.

Let me know :)

**Comment by JuanCaicedo** [comment]
I'm out of town, but I think 10/10 sounds like a good date based on those reasons. @danpaz?

(I'm planning on going to EmpireNode too!)

**Comment by danpaz** [comment]
SGTM. Let's do it!

**Comment by robbiethegeek** [comment]
@danpaz so can I schedule? do you need to clear it with your company?

**Comment by danpaz** [comment]
Yup it's been cleared, go ahead and schedule it :smile:

**Comment by robbiethegeek** [comment]
Was a great event!
