### ISSUE TITLE
November 2015 - NodeSchoolDC

### ISSUE THREAD

**Issue by robbiethegeek** [NodeDC/organizers#27]
Looking at the calendar and the holiday I am suggesting 11/21 the Saturday before Thanksgiving.  Seems like an open day and would love to get this scheduled and continue the momentum.  Also if we have it on the calendar we can get it promoted at the upcoming events including NationJS.

Team Fluencia let me know :) @JuanCaicedo @danpaz 
/cc @joshfinnie

**Comment by JuanCaicedo** [comment]
I think we should be all good, I'll check with the powers that be!

**Comment by robbiethegeek** [comment]
@JuanCaicedo any word?

**Comment by JuanCaicedo** [comment]
Yes, good to go!

**Comment by robbiethegeek** [comment]
Posted!
