### ISSUE TITLE
NodeSchool December

### ISSUE THREAD

**Issue by JuanCaicedo** [NodeDC/organizers#28]
@danpaz @robbiethegeek

Let's talk about whether we can do a nodeschool in December, since I know both Dan and I are going to be out of town.

I'll be in Oregon from the December 6-27

**Comment by danpaz** [comment]
Hmm I'll be gone Dec 19 - Jan 3. I could probably do Dec 12 though?

**Comment by robbiethegeek** [comment]
I could likely do 12/12 Let's see if we can lock it up soon (I have a doctor's appointment I will shift once confirmed :) )

**Comment by JuanCaicedo** [comment]
I'll ask Caroline now

**Comment by robbiethegeek** [comment]
Are we a go for this?

**Comment by JuanCaicedo** [comment]
Shoot, I thought we had posted and announced this already. Yes, we're good to go.

**Comment by JuanCaicedo** [comment]
I think we should just make a schedule of all the dates we want for the next 6 months and make events. I'll look at a calendar over the weekend and propose some

**Comment by robbiethegeek** [comment]
Created and This can be closed I don't have the permissions :)
