### ISSUE TITLE
NovaNode + NodeDC

### ISSUE THREAD

**Issue by danmactough** [NodeDC/organizers#29]
Greetings, NodeDC and NovaNode Organizers! @NodeDC/organizers 

After a few conversations, NovaNode organizers @JuanCaicedo and @danpaz and I have concluded that it would benefit our communities to meld the NovaNode meetup group into the NodeDC meetup group.

The vast majority of NovaNode's members are also members of NodeDC, so there doesn't appear to be a good reason to have two meetups serving the same community.

In you have any concerns about these plans, please speak up today. Please comment on this issue (or privately via email, if you must).
## The Plans
- Any current NovaNode organizers who aren't NodeDC organizers will made NodeDC organizers.
- Any organizers who need access to the @NodeDC twitter account will be given access.
- Later this week, we'll announce our Call For Proposals for Q1 2016.
- As of January 1, 2016, meetups will be organized under the NodeDC meetup group.

**Comment by adunkman** [comment]
:+1: :heart:

**Comment by jkeam** [comment]
yes yes!!

**Comment by joshfinnie** [comment]
double :+1:

**Comment by sandinmyjoints** [comment]
Even from way over here, this seems like a good idea!

**Comment by mcwhittemore** [comment]
:+1:

**Comment by jonathana** [comment]
+1

**Comment by ahaurw01** [comment]
:metal: :guitar:

**Comment by danmactough** [comment]
I updated the description to skip the "wind-down" things since we're really just going to see how it goes this coming quarter. We may realize that NovaNode should continue organizing activities separately.

**Comment by danmactough** [comment]
Also, we'll be scheduling a meetup at Fluencia at least once each quarter.

Going to close this issue as I think it's purpose has been served. :smile:
