### ISSUE TITLE
Reviewing submitted proposals

### ISSUE THREAD

**Issue by adunkman** [NodeDC/organizers#3]
How should we do it? 

Last time around, we (I) removed all personally identifiable information from the submissions and then emailed them around to @danmactough, @joshfinnie, and @mcwhittemore.

**Comment by mcwhittemore** [comment]
Should proposals be issues in github? Than we can comment on them and vote with +1s?

**Comment by jonathana** [comment]
Can it just be shared out over Google docs?

**Comment by danmactough** [comment]
> Should proposals be issues in github? 

That would be great. Speakers could make pull requests for proposed talks.

**Comment by adunkman** [comment]
It can be anything if we dream! :performing_arts: 

CascadiaJS did their proposals via GitHub PRs, and I felt a bit exposed when creating the PR. I double and triple checked my PR since it was so public.

I’m not sure if that was just me, but if it wasn’t just me, I’m not sure if we want that barrier to entry — I think part of this process that’s great is that it’s very welcoming to new presenters, and it sets presenters on a path which could end up with them speaking at conferences. I’d hate to turn away people because they were a bit shy from publishing their ideas publicly.

That being said, maybe i’m over-thinking it! 

It’s also worth noting that it’d require our speakers to have GitHub accounts, which we don’t require now.

**Comment by adunkman** [comment]
> CascadiaJS did their proposals via GitHub PRs, and I felt a bit exposed when creating the PR. I double and triple checked my PR since it was so public.

After re-reading this, I was thinking “What’s the difference between this and what we did in December? You’re still publishing your ideas, just to a smaller audience!”.

I think the difference to me is what happens when you don’t get chosen to speak. From our last CFP, the people who weren’t chosen to speak weren’t published. We didn’t let people know who they were, so there (hopefully) wasn’t any embarrassment.

**Comment by danmactough** [comment]
> I’m not sure if we want that barrier to entry

Yeah, this is very true.

**Comment by ryan-roemer** [comment]
Hi DC folks!

> CascadiaJS did their proposals via GitHub PRs, and I felt a bit exposed when creating the PR. I double and triple checked my PR since it was so public.

Just adding a bit more background here for CascadiaJS, we actually have two routes to submitting talks -- the public repo and out-of-band emails, which we privately aggregate. The public repo has the majority of the talks and is great for (1) building interest generally, and (2) helping folks avoid overlap, while the private email option gives folks a more comfortable way to submit talks.

**Comment by danmactough** [comment]
@ryan-roemer I was thinking about two-track, as well. Thanks for the clarification!

**Comment by mcwhittemore** [comment]
I feel the fears about only public 100%. I was more thinking about a way for us to comment on the talk proposals and it seemed worth while to put them into a github repo (maybe a private one) and have the conversations there. I don't know about you, but I find it a lot easier to read a bunch of issue conversations than email.

**Comment by adunkman** [comment]
Okay! For this go-around, I’ll just create a Google Spreadsheet and link it here. I’m going to remove personally identifiable information from the submissions in an attempt to keep our decisions based solely on the subject matter in the talk and to avoid subconscious bias.

We can then drop inline comments on the Google Spreadsheet and rock and roll!

**Comment by danmactough** [comment]
:+1: Thanks @adunkman

**Comment by adunkman** [comment]
Here’s [the anonymized responses](https://docs.google.com/spreadsheets/d/1aTsJOL-we6cXEaFUoLFDRjeF3EZg38Mqwt1O9SuVU8U). Feel free to drop inline comments in the spreadsheet, or comment here with talks you’d like to see… or something. Do what you think is right!

**Comment by mcwhittemore** [comment]
I moved all of these response to github issues and grouped them into a single milestone.

https://github.com/NodeDC/organizers/milestones/Spring%20Talks%202015

@adunkman how many talks are we trying to have before the next CFP?

**Comment by adunkman** [comment]
> @adunkman how many talks are we trying to have before the next CFP?

A number of them! I don’t have a specific number, but I could see having another CFP either in the fall or winter again. 

We previously did December (and this time in April). It seemed to work out pretty well. This would put us on track to have another CFP in August or so. 

Back-scheduling, we’ve been having roughly two meetups per month, one talk and one Node Night. This would put us at a talk for May, June, July, and August — notable mention to #18 which might be considered here. 

So, that would put us at three or four talks, if we follow all of that. I’m open to not do that, though, if somebody convinces me of something better!

**Comment by adunkman** [comment]
Just ran a tentative schedule:

```
thurs 5/28 novanode talk
thurs  6/4 node night
sat   6/13 novanode unconference
thurs 6/18 talk
wed    7/1 Lin Clark (talk?)
thurs 7/16 talk (something nodebots related?)
sat   7/25 nodebots day
thurs 7/30 node night
thurs 8/13 talk
thurs 8/27 node night
```

Obviously these dates are pretty tentative, and will likely move around a bit — but that would put us at 3 node nights and 3 talks before the end of August.

**Comment by danmactough** [comment]
@adunkman Lin is 6/1, not 7/1

**Comment by adunkman** [comment]
Just met with @danmactough and revised the schedule:

```
(sat  6/13 novanode unconference)
thurs 6/18 talk
thurs  7/2 node night
thurs 7/16 talk (something nodebots related?)
(sat  7/25 nodebots day)
thurs 7/30 node night
thurs 8/13 talk
thurs 8/27 node night
```

Emailing to UberOffices now to see if these dates work for them!

**Comment by adunkman** [comment]
For posterity: 

> Hey Jazmin,
> 
> It was great to see you the other night! 
> 
> We just threw together a tentative schedule for the rest of our dates until September — I know you mentioned that you were trying to stick to two events per week in your space. Do these dates work for you? 
> 
> Thursday, June 18
> Thursday, July 16
> Thursday, July 30
> Thursday, August 13
> Thursday, August 27
> 
> Thanks for being a great host to us! Let me know! 
> 
> Andrew

I didn’t ask for July 2nd — thinking that we might want to do that as a Nova Node meetup — what do you think @danpaz and @JuanCaicedo?

**Comment by adunkman** [comment]
@joshfinnie how does 7/2, 7/25, and 8/27 (all dates tentative) work for you for node nights?

**Comment by JuanCaicedo** [comment]
@adunkman I think @danpaz is going to be out of town then, but I'll be here. Let me check with Fluencia to be sure, but that sounds good to me!

**Comment by adunkman** [comment]
Received a response from UberOffices:

> Hi Andrew!
> 
> Thank you for the info! Unfortunately we can not host 2 events a month since its busy season however, if you would like to pick one of the days in July and August we can put you in the calendar! June 18th is already book as well.
> 
> Thanks and talk to you soon! 

I’m not sure I really love thinning out our events to one a month, so we’re left with a question — take UberOffices up on their offer of one event a month and then find another space for the alternating events, or just find another space which can host us twice a month. 

I’d hate to pass up the space, since we can book it and the events will happen — but at the same time, I don’t love making people bounce back and forth for events. 

Thoughts?

**Comment by robbiethegeek** [comment]
I am definitely not going to be at 7/2 event, I am heading out of town for the 4th of July with my entire family.

**Comment by danmactough** [comment]
Let's take whatever free space we can get

**Comment by jonathana** [comment]
+1 what Dan Said
