### ISSUE TITLE
Jan - June 2016 NodeSchoolDC events

### ISSUE THREAD

**Issue by robbiethegeek** [NodeDC/organizers#30]
So I have outlined on the DC Javascript calendar the next 6 months of events based on the 3rd Saturday of the month:

1/16/16
2/20/16
3/19/16
4/16/16
5/21/16
6/18/16

@JuanCaicedo @danpaz want to confirm with Catherine?  @joshfinnie / @danmactough any worries about us claiming the 3rd Saturday of the month for these events?

@JuanCaicedo @danpaz want to up the timing like we discussed? to 4 hours (I suggest 12pm - 4pm)

**Comment by JuanCaicedo** [comment]
Thanks for doing that! I like the dates, though I'm going to be out of town for the January one (the 18th is MLK. Are you staying in town @danpaz?).

For time, I'd rather do 1pm-5pm. That way I could go to Code&Coffee which ends at noon and get food before we start. I also think most people do lunch around 12, so they wouldn't arrive until 1 anyway?

**Comment by danpaz** [comment]
Those dates wfm except for maybe MLK day, that and I'm getting married 5/22 :ring: :smile:

**Comment by JuanCaicedo** [comment]
What do you guys think of doing each of those a week earlier?

**Comment by robbiethegeek** [comment]
I am ok with both the bumping of the dates and the hour shift to 1-5pm will open up brunch possibilities for me :)

**Comment by joshfinnie** [comment]
brunch ++

**Comment by danmactough** [comment]
> any worries about us claiming the 3rd Saturday of the month for these events?

I've heard that the Saturday NodeSchool events have pretty much been drawing a different crowd every time. So, as far as attendees are concerned, I don't think we have anything to worry about.

I think we'll be having meetups on the 3rd Thursday. As long as that's not a problem for organizers, I think it's a nice thing to be able to announce at the meetups: "And we having a NodeSchool on Saturday..." (Or vice versa to announce at the NodeSchool's that precede the meetups.)

There are only so many weeks in the month. :smile:

**Comment by robbiethegeek** [comment]
I have all the events created as drafts on meetup.com once I get a final :+1: from @danpaz / @JuanCaicedo our gracious hosts I will make them active and add them to nodeschool.io

**Comment by adunkman** [comment]
:heart: :heart: :heart:

**Comment by robbiethegeek** [comment]
bump for confirmation @JuanCaicedo @danpaz  :)

**Comment by JuanCaicedo** [comment]
@robbiethegeek I asked Caroline to request these dates with our building, I'll let you know as soon as we know:

> January 23th, 2016 (1-5pm)
> February 20th, 2016 (1-5pm)
> March 19th, 2016 (1-5pm)
> April 16th, 2016 (1-5pm)
> May 28th, 2016 (1-5pm)
> June 18th, 2016 (1-5pm)

**Comment by robbiethegeek** [comment]
I shuffled the dates as requested:

1/23/16
2/20/16
3/19/16
4/16/16
5/28/16
6/18/16

**Comment by danpaz** [comment]
Let's think of a back up plan in case this snowstorm hits this weekend?

**Comment by JuanCaicedo** [comment]
Stupid snow storm. We could knock it back a week?

**Comment by robbiethegeek** [comment]
The next saturday is AlterConf : http://www.alterconf.com/sessions/washington-dc I am heading to that.  If we need to let's cancel or see if next Sunday 1/31/16 would be ok if possible.

**Comment by robbiethegeek** [comment]
We also have people RSVPing yes today, if the weather doesn't get terrible would be cool to host it, a huge amount of signups.

**Comment by joshfinnie** [comment]
Maybe we should send a note that we're aware of the weather predictions and are going to make a decision later once more info is available?

**Comment by jkeam** [comment]
Ya I like that idea; clear and open communication.

**Comment by robbiethegeek** [comment]
OK will send a message to all Meetup attendees and post a comment.

**Comment by JuanCaicedo** [comment]
SGTM, I would rather not cancel as well, and since we're along the metro line, we'll probably have no problems.

**Comment by danpaz** [comment]
I'm good with playing it by ear, but we'll have to make the call asap so the building knows whether or not to turn on the heat for us. Note that metro could shut down in the case of >8 inches of snow: http://www.wmata.com/getting_around/safety_security/snowmap.cfm

**Comment by JuanCaicedo** [comment]
`^` That's a pretty big problem. Let's wait until tomorrow midday to see how the forecast has changed, but  in that situation we might have to veer on the safe side. @robbiethegeek that would be cool if you can post, if not I can

**Comment by JuanCaicedo** [comment]
I posted a comment saying we will be rescheduling to Sunday 1/31 (bummmmmer). I'm going to update the event and send out an email.

**Comment by robbiethegeek** [comment]
Sounds good.

**Comment by JuanCaicedo** [comment]
@robbiethegeek @danpaz What do you think of announcing all the events right now? I'd like to have them all on my calendar, and I doubt Caroline will say any of them are a problem (at least she didn't mention anything when I sent her the dates). I'll follow up with her before each event to make sure we have the space. Then we can also close this issue and just make individual ones if we need to talk about something for an event.

**Comment by robbiethegeek** [comment]
Sure I am game. Once you both :+1: I will make live

**Comment by danpaz** [comment]
Sounds great :+1:

**Comment by robbiethegeek** [comment]
Done and tweeted about it https://twitter.com/NodeSchoolDC/status/691636564078669825

**Comment by robbiethegeek** [comment]
Closing this issue since it is scheduled an done.  I will tweet each of the events from the NodeSchoolDC twitter as they arrive.
