### ISSUE TITLE
Winter 2016 Call for Proposals

### ISSUE THREAD

**Issue by danmactough** [NodeDC/organizers#31]
Taking @adunkman's previous work as a model, about to send the following announcement to the meetup group:

> Winter Call for Proposals
> 
> Hello Friends!
> 
> Let it snow! Winter is here, and we’re opening a Call for Proposals. We’ll use the content that you submit to plan the next few months of meetups.
> 
> If you’re not familiar with the concept of a Call for Proposals, we’re just formally asking you to spend a few moments to consider if you’d like to share content with Node.DC through a presentation or workshop.
> 
> We’re opening the Call for Proposals today, and it will remain open through December 31. Send any questions to Dan (danmactough@gmail.com) or tweet at us @NodeDC.
> 
> Call for Proposals: http://bit.ly/1Qt5boy.
> 
> Thank you for considering sharing your knowledge! 
> Dan

**Comment by danmactough** [comment]
The CFP form, pretty much a carbon copy:

> Call for Proposals: Node.DC — Winter 2016
> Let it snow! Winter is here, and we’re opening a Call for Proposals. We’ll use the content that you submit to plan the next few months of meetups.
> Thank you for considering sharing your knowledge with the Node.DC community!
> 
> Ideally, your content will take between 45 minutes and an hour to share. If that format doesn’t work well for your idea, submit it anyways, and let us know in the description! Great ideas bend the rules when appropriate. :)
> - Required
>   ##### Name *
>   We’d like to call you by the correct name — if your submission is accepted, this is how we’ll refer to you.
>   [textbox]
> 
> ##### Email Address *
> 
> We’ll contact you after the Call for Proposals ends to let you know the status of your submission.
> [textbox]
> 
> ##### Title *
> 
> A short, descriptive title for your content. Try to avoid being too clever.
> [textbox]
> 
> ##### Abstract *
> 
> A few sentences describing your content. A good abstract describes not only what you’re going to cover, but also how you hope your audience will change after hearing your content.
> [texarea]
> 
> ##### JavaScript Outside the Browser
> 
> We’re currently focusing on presenting content that centers around JavaScript running outside of web browsers.
> - [ ] Not browser-based: My content is centered around JavaScript executing outside of a web browser.
> - [ ] Browser-based: My content is centered around JavaScript executing in a web browser.
> 
> ##### Will you be present in Washington, DC?
> 
> We are open to receiving presentations remotely, if you are unable to be present with us in Washington, DC.
> - [ ] I will be in Washington, DC while presenting.
> - [ ] I will be presenting remotely.
> 
> ##### Prerequisites
> 
> What do you expect someone to know to understand your content?
> [texarea]
> 
> ##### Additional Information
> 
> Is there anything else you think we should know about?
> [texarea]
> 
> ##### Code of Conduct *
> 
> The Node.DC community is made up of a mixture of professionals and volunteers with different levels of understanding and personal beliefs. This diversity is one of our strengths, and in an effort to enrich and protect our community we’ve enacted a Code of Conduct that can be read online at https://github.com/NodeDC/CodeOfConduct.
> - [ ] I have read, understand, and agree to follow the Node.DC Code of Conduct.

**Comment by danmactough** [comment]
:point_up: @danpaz @JuanCaicedo @joshfinnie @robbiethegeek :point_up:

**Comment by danpaz** [comment]
Looks good! I wouldn't change a thing

**Comment by danmactough** [comment]
I think I'll send the meetup announcement and do the tweeters in the morning.

**Comment by robbiethegeek** [comment]
Sounds great I will echo on nodeschooldc

**Comment by danmactough** [comment]
##### Announced! - Analytics http://bit.ly/1Qt5boy+

##### Scheduled tweets
- Sun 12/20 9:00am
- Tue 12/22 11:00am
- Sat 12/26 10:30am
- Mon 12/28 3:00pm
- Wed 12/30 3:22pm
- Thu 12/31 9:37am

**Comment by danmactough** [comment]
CFP is closed. We received 7 proposals, and I think all of them sound good. I'll be posting each proposal, anonymized, as a separate issue. We can discuss each proposal in its comments, and have any meta-discussion here.

**Comment by JuanCaicedo** [comment]
Awesome! 

Moving forward, I like the idea of continuously accepting proposals through a repo the way that [CharmCityJS](https://github.com/charmCityJs/talks/issues) does it. I like that because it's transparent, easy to manage, and we can get proposals when it's convenient for the proposer, instead of when it's convenient for us, which I think will encourage more participation. I can open up a separate issue if you think it needs some discussion.

**Comment by danmactough** [comment]
> I can open up a separate issue if you think it needs some discussion.

Please do!

> instead of when it's convenient for us

Convenient for us is pretty important, too. :smile:

**Comment by danmactough** [comment]
NationJS just announced that they will be having a Node conference on March 11. Currently, we are planning on having a Meetup and a NodeSchool the following week. @robbiethegeek It might be cool to change the NodeSchool to March 12, the day after the conference.

**Comment by danmactough** [comment]
Oh, but my point in posting on this issue was to ask if we should consider rescheduling the tentatively scheduled March 17 meetup. We may want to do another pre-conference meetup the night before.

**Comment by robbiethegeek** [comment]
I can move it, I will likely not be available (my 1st wedding anniversary is 3/14/16 and I think my wife and I are going away).  I leave it to @JuanCaicedo and @danpaz  if they want to run it without me.

**Comment by danpaz** [comment]
So tentatively the nationjs pre-party would be 3/10/16, the nodeschool would be 3/12/16, and the March talk would be a different day? Or would the pre-party === the March talk?

**Comment by danmactough** [comment]
> Or would the pre-party === the March talk?

That's what I was thinking, but it's a good question. What do you think? I think another meetup the following week would be overkill. We could bump it back a week, but still seems like a lot of talks in such a short span of time.

**Comment by joshfinnie** [comment]
I agree with @danmactough especially if the pre-party follows the same line as it did for this past NationJS where it's 3 lightning talks... it felt very meetup-y :-)

**Comment by danpaz** [comment]
Yup a single March pre-party/talk event WFM

**Comment by robbiethegeek** [comment]
I think a pre-party event is great, let's move forward with that (and no meetup the next week).  I think doing a Thursday, Friday, Saturday may be too much NodeDC fun and games anyone else?

**Comment by danmactough** [comment]
I'm going to announce #37 for the 1/21 meetup and @JuanCaicedo, @danpaz and I discussed.

**Comment by danmactough** [comment]
I've announced #35 for the 2/18 meetup and scheduled the twitters.

**Comment by JuanCaicedo** [comment]
I'm going to close this since we're scheduled through May (and we're discussing those in their own issues)
