### ISSUE TITLE
Static Code Analysis for Modern Node

### ISSUE THREAD

**Issue by danmactough** [NodeDC/organizers#32]
# Static Code Analysis for Modern Node

This presentation seeks to provide a strong argument for using static code analysis in modern node projects and enough concrete technical knowledge for attendees to feel comfortable adding or expanding static analysis tooling in their own projects. The first part presents a taxonomy of static analysis methods/tools and real-world examples of how they are useful. The latter portion focuses on one particular tool (eslint) and how to extend its functionality with a plugin and rules.
- Not browser-based: My content is centered around JavaScript executing outside of a web browser.
- I will be in Washington, DC while presenting.
## Prerequisites

While background in abstract syntax trees and recursive descent parsing is helpful, enough context on these topics will be presented such that a developer with a reasonable grip of any programming language should understand the material.
## Additional Information

The earliest this material would be ready to present is late February.

**Comment by JuanCaicedo** [comment]
Linting is an essential part of javascripting, I think this would be an awesome topic to go over! It will be good as an introductory topic for new devs. For more advanced devs, it might be stuff they're already familiar with, but they might still learn a few new tricks.

Did they provide any information about the length of the talk?

**Comment by danmactough** [comment]
> Did they provide any information about the length of the talk?

No. We didn't ask for that information. :disappointed:

**Comment by danpaz** [comment]
Linting could either be a beginner or advanced topic depending on how it's approached. Given one of the prerequisites is to have a background in ASTs there might be some discussion how linters are built. Anyway, sounds good to me!
