### ISSUE TITLE
Composition Over Inheritance

### ISSUE THREAD

**Issue by danmactough** [NodeDC/organizers#33]
# Composition Over Inheritance

OOP has been a staple in the JS community for a long time. But this is a farce - there is another way! You should focusing on highly composable, independent entities rather than highly coupled, hierarchical based monstrosities.
- Not browser-based: My content is centered around JavaScript executing outside of a web browser.
- I will be in Washington, DC while presenting.
## Prerequisites

They should have a basic understanding of object oriented programming (although I'll briefly go through it) and a working understanding of JavaScript.

**Comment by JuanCaicedo** [comment]
Definitely a useful topic, for both beginners and more advanced!

**Comment by JuanCaicedo** [comment]
My vote would be to do this as the January talk.

**Comment by danmactough** [comment]
> My vote would be to do this as the January talk.

@JuanCaicedo Yeah, we'll have to get in touch pretty soon with whomever it is we'd like to speak in January. :grin:

**Comment by danpaz** [comment]
I would beware of this becoming a highly opinionated talk, pitting one programming style against another, etc. The concept of composition over inheritance is a good one to hear about, but OOP and composition are not necessarily mutually exclusive.

Something that would be super interesting to me is an overview of design patterns, best practices, and gotchas in node. Composition over highly nested class hierarchies could be one example of these.

**Comment by joshfinnie** [comment]
Yeah, I agree with @danpaz this could run away quickly, and with ES2015 adopting solid OOP principals with honest classes this might be a bit long in the tooth... though I know there's a lot of people still using !ES2015.

**Comment by danmactough** [comment]
Hey, @recursivefunk! We want you to present this talk at NodeDC! We're looking at April 21 and May 19 as the available dates. Can you make both of those? Do you have a preference?

**Comment by recursivefunk** [comment]
Hey @danmactough lets do April.

For those concerned about this being an opinionated talk - you're absolutely right! But that's the beauty of it. I like to think that we're a community of independent thinkers with different experiences. Don't worry, this isn't a rant against OOP and classes, I have thoughtful, rational arguments here. I'll be sure to have a disclaimer to tell folks these are my opinions. But if you're looking for more of an instructional talk that more or less re-hashes a JS text book this isn't the talk you want! 

Let me know!

**Comment by JuanCaicedo** [comment]
SGTM, strong opinions lead to great beer covo's after!

**Comment by danmactough** [comment]
> I like to think that we're a community of independent thinkers with different experiences.

Hell, yeah. :+1:

**Comment by danmactough** [comment]
Announced: http://www.meetup.com/node-dc/events/229641035/
Tweets tweeted https://twitter.com/NodeDC/status/730789686629765121 and scheduled.
