### ISSUE TITLE
Express from scratch

### ISSUE THREAD

**Issue by danmactough** [NodeDC/organizers#34]
# Express from scratch

Using no 3rd party code, we'll build express from the ground up.

Well use the http module and plain ole js to build a web framework - express clone.
- Not browser-based: My content is centered around JavaScript executing outside of a web browser.
- I will be in Washington, DC while presenting.
## Prerequisites

The basics of HTTP. Familiarity with express.
## Additional Information

This would be such a rad talk.

**Comment by JuanCaicedo** [comment]
I like the idea of breaking down the design patterns and source code of another project by building it from the group up. It's a little more complicated if the speaker is planning on live coding, but doable if they know the framework and their demos really well. Sounds cool!

**Comment by danpaz** [comment]
+1

**Comment by joshfinnie** [comment]
I like this idea! I like this idea a lot. :+1:

**Comment by danmactough** [comment]
Hey, @jshawl! We want you to present this talk at NodeDC! We're looking at April 21 and May 19 as the available dates. Can you make both of those? Do you have a preference?

**Comment by jshawl** [comment]
@danmactough both of those dates work for me. No preference! Thanks!

**Comment by danmactough** [comment]
@jshawl May it is! Looking forward to it!

**Comment by jshawl** [comment]
@danmactough @joshfinnie apologies for the late notice - I realized I'll be out of town May 19. Is it possible to switch with someone else's date?

**Comment by danmactough** [comment]
@recursivefunk expressed a preference for April 21, but maybe he can switch to May 19. Johnny Ray?

**Comment by recursivefunk** [comment]
@danmactough May 19th is fine for me. In fact, it's preferable!

**Comment by danmactough** [comment]
:tada: There you go, @jshawl! April 21 is yours.

**Comment by danmactough** [comment]
Thanks, @recursivefunk!

**Comment by jshawl** [comment]
awesome thanks yall!

**Comment by rektide** [comment]
Sweet time!
