### ISSUE TITLE
Hello World of ES2015 in Node Core

### ISSUE THREAD

**Issue by danmactough** [NodeDC/organizers#35]
# Hello World of ES2015 in Node Core

We are going to introduce ourselves to as much of the full set of ES2015 features available in Node core (v4.x and v5.x) as we can by assigning everybody attending the task of writing a "hello world" script that uses one (or more) ES2015 feature and then briefly sharing what they learned about the feature.
- Not browser-based: My content is centered around JavaScript executing outside of a web browser.
- I will be in Washington, DC while presenting.
## Prerequisites

Everyone will need to be prepared to write some Node and be prepared to present their code to the group.

**Comment by JuanCaicedo** [comment]
Cool idea, I like having something interactive where people can all do stuff and share what they've learned. I think we should have a couple regular-style talk meetups before, and maybe do this in the spring, since it's harder to execute.

**Comment by danpaz** [comment]
I love the idea of doing a meetup in the style of the [core modules one](http://www.meetup.com/node-dc/events/187038062/) but for ES2015 features. :+1:

**Comment by jonathana** [comment]
+1

**Comment by joshfinnie** [comment]
this is 1000% for me...

**Comment by JuanCaicedo** [comment]
We've decided on this for the February 18th meetup. The submission was by @danmactough, so we'll have him lead it. Since it's going to be an interactive, feel free to add any thoughts about additional things you'd like to see/cover in this!

**Comment by jonathana** [comment]
Don't forget https://github.com/mcwhittemore/deck-lightning as a way to
review the output at the end.

**Comment by danmactough** [comment]
@jonathana Thanks for linking that. I couldn't remember what it was called.

**Comment by mcwhittemore** [comment]
Oh. Poor old deck lighting. :)

**Comment by jonathana** [comment]
Go Deck Lightning you're parsing up the markdown files
(Deck Lightning, go Deck Lightning)
Go Deck Lightning you're spitting out the HTML
(Deck Lightning go Deck Lightning)
You are so keen the geeks'll scream for Deck Lightning
Go, go, go, go, go, go, go, go, go, go
