### ISSUE TITLE
Fine Art in Node.js

### ISSUE THREAD

**Issue by danmactough** [NodeDC/organizers#37]
# Pure Science or Artsy Fartsy

So often we talk about programing as putting pieces together. We use words like engineering to imply that we have solid plans and scientific reasons for doing what we do. 9 months ago I got really burning out, in part because of this kind of thinking. I'm not a planner, I'm a doer, and so I started just smashing pixels together. The result was more like science then anything I'd done before, but calming and therapeutic like art.

In this talk I'll cover a bit of what I did (the art) and theorize on why we should do it more (the science).
- Not browser-based: My content is centered around JavaScript executing outside of a web browser.
- I will be in Washington, DC while presenting.
## Prerequisites

I think anyone with a basic idea of computer science will be good.
## Additional Information

[links to example results removed to anonymize the proposal]

**Comment by JuanCaicedo** [comment]
Hmmm, I'm not really sure what this submission is about. Is it about burn out and and the approach the author used to get out of it, which felt more like art than engineering?

**Comment by danpaz** [comment]
Agreed on needing more information. Maybe @danmactough can share the example results with the organizers by email?

**Comment by danmactough** [comment]
![image](https://cloud.githubusercontent.com/assets/357481/12097606/7511f054-b2ea-11e5-85c0-0bdaeff47dca.png)

**Comment by danmactough** [comment]
![image](https://cloud.githubusercontent.com/assets/357481/12097618/8978bdc0-b2ea-11e5-9dfc-75bafed57407.png)

**Comment by danmactough** [comment]
![image](https://cloud.githubusercontent.com/assets/357481/12097646/bc46cf58-b2ea-11e5-84ed-2ed86515472a.png)

**Comment by joshfinnie** [comment]
Okay, I am 100% on board... those examples are killer and would love to hear this talk! Agreed, however, based on the proposal I would be a bit weary about this one.

**Comment by mcwhittemore** [comment]
This is my proposal. Not sure if these are supposed to be anonymous, but as Node.DC takes talks via github I'm going to guess it doesn't matter.

I agree with @JuanCaicedo that my original proposal is a little more than dual-minded and that fixing that is key to a good talk. I really just want to share the fun node-art I've been making and thought giving some background to why I started making it would help tell a story. I'm open to suggestions.

**Comment by JuanCaicedo** [comment]
@mcwhittemore Ahhh, looking at the images and hearing you say that makes a lot more sense, I was thinking it was about approaching Node as art, not about making art through Node. Sounds cool!

**Comment by johnelliott** [comment]
This story/topic sounds like something that will stimulate thoughts and discussion with other meetup attendees, so I really hope we can hear this.

**Comment by mcwhittemore** [comment]
So what I really want to do here is make an image while I give a talk, but images take a while to make (there are a lot of pixels in 2000 instagrams). One idea I had was to create a queue and get everyone present to help me crunch the image. Thoughts? I could also just walk through the code for a few of the images I've made and talk about how a hair brain idea with an artistic end often forces you to learn new tools. Any guidance?

**Comment by jonathana** [comment]
Can you show an iterative process to the final image?  If you do that
offline you can compress time by just showing the steps along the way and
the output images that were generated along the way.

J

**Comment by mcwhittemore** [comment]
I'm hoping to try re-creating st paul's in the next week. I'll see if I can capture the steps and report back.

**Comment by JuanCaicedo** [comment]
Seems like there's some good interest, so we're going to be have this talk for the January 21st meetup!

@mcwhittemore I think you've been talking to @danmactough right? Let me know when you're putting it together if you'll need anything special, and I'll check in with you a little closer to the date.

**Comment by mcwhittemore** [comment]
@JuanCaicedo sounds great.

**Comment by mcwhittemore** [comment]
I don't think we should update the meetup, but I've titled the talk `Fine Art in Node.js` so I updated it here.

**Comment by danmactough** [comment]
:+1:

**Comment by JuanCaicedo** [comment]
Awesome way to start off the year, thanks @mcwhittemore !

**Comment by mcwhittemore** [comment]
Here are my slides: http://mcwhittemore.com/make-art.html
