### ISSUE TITLE
Using python machine learning stuff in node.js

### ISSUE THREAD

**Issue by danmactough** [NodeDC/organizers#38]
# Using python machine learning stuff in node.js

I like writing web servers in node and doing machine learning stuff in python. For this talk I'll show you how to set stuff up so that node and python talk to each other. We'll also cover installation, hot-reloading, testing, and production deployment of the setup.
- Not browser-based: My content is centered around JavaScript executing outside of a web browser.
- I will be in Washington, DC while presenting.
## Prerequisites

Maybe knowing a little about sockets is good but not required to use the setup. Same with python, it would help to know a little but it'll probably still be a useful/interesting talk to people who don't do python. The same or similar concepts can be used by someone who may want to use any other language, like for instance utilizing a spacecraft orbit propagator from JPL written in Fortran 95.

**Comment by JuanCaicedo** [comment]
Sounds interesting, definitely something I don't know how to do. This would potentially get some people in the python community who are interested in node to come out, which would be fun!

**Comment by danpaz** [comment]
Based on the description it sounds like its more about setting up a python project to work with node, as opposed to the title which is about machine learning. Maybe we can ask the speaker which direction they'd take it in? Either way it sounds interesting to me!

**Comment by joshfinnie** [comment]
python and node?? hmmm, who would have thought :+1:
