### ISSUE TITLE
Node Unconference [June 13?]

### ISSUE THREAD

**Issue by JuanCaicedo** [NodeDC/organizers#4]
We've been talking about hosting a NovaNode/NodeDC unconference. Since NodeConf this year is an unconference, we talked about doing this at that same time on Saturday, June 13th. Our event would be in Rosslyn.

Feel free to comment any thought about such an event on here!
##### These are the things I wanted to gage
- How interested would the community be?
- Does the proposed date (Saturday, June 13, 9AM-4PM) work for everyone?
##### What is an "un"conference?

It's basically a conference without set speakers or topics. This is what goes on at an unconference: 
1. All attendees write down topics that they would like to discuss / learn about on index cards and place them on a table. 
2. All attendees vote on their favorite 3 topics by drawing dots on the index cards. 
3. The organizers prioritize the list of topics based on most votes and form a schedule of sessions. 
4. If your index card was picked as a session, you are in charge of moderating (leading the discussion / asking questions). 
5. Everyone learns a lot, has a ton of fun, and gets to know more people in the community!

@adunkman @danmactough @danpaz

**Comment by jkeam** [comment]
+1 to the idea, but not sure about the date.  Since it's the same time as NodeConf, you can only attend one.  Thoughts?

**Comment by JuanCaicedo** [comment]
The idea was to have an "If you can't make it to NodeConf (in CA)" event.  But if people going to NodeConf really wanted to attend a local event like this, we could then plan on a later date.

**Comment by danmactough** [comment]
@JuanCaicedo Maybe the weekend _after_ NodeConf? It could still be an "If you couldn't make it to NodeConf" event, and people who went to NodeConf might be interested in leading some sessions that recap and/or follow-up on NodeConf sessions.

**Comment by jkeam** [comment]
+1

**Comment by adunkman** [comment]
@jkeam are you planning on going to NodeConf this year?

**Comment by jkeam** [comment]
haha debating it, but not sure yet.  are you?

**Comment by adunkman** [comment]
@jkeam not this year for me, but definitely considered it!

**Comment by JuanCaicedo** [comment]
One of our organizers is going to be out of town for the second half of June, so I think we're going to stick with June 13th. The event will be up sometime next week, I'll let you all know!

**Comment by adunkman** [comment]
Sweet! Thanks for the heads up, this seems like an exciting event. :)

**Comment by joshfinnie** [comment]
I really like this idea, so I am going to chime in with my :+1:

**Comment by JuanCaicedo** [comment]
Here's the link to the event, it's happening! I'm also going to close this issue.

http://www.meetup.com/Nova-Node/events/221268375/
