### ISSUE TITLE
The Rebirth of NodeNights

### ISSUE THREAD

**Issue by joshfinnie** [NodeDC/organizers#40]
Okay, we need to get these organized again... I severely dropped the ball on these and I think they're such an important part of this community. Let's get some planned on the books!

**Comment by danmactough** [comment]
:+1: Get 'em on the calendar. We have space. :tada:

**Comment by JuanCaicedo** [comment]
Yeah, I've been thinking about this too. What do y'all think of 2/4 at Fluencia? I'll check with the powers that be to see what they think.

**Comment by joshfinnie** [comment]
Yeah, I really liked the alternate Fluencia/DC pattern we had, @JuanCaicedo! Let's ask about 2/4... would be a great start.

**Comment by joshfinnie** [comment]
@danmactough is there an actual calendar?

**Comment by danmactough** [comment]
> is there an actual calendar?

I'm referring to the Javascript DC shared Google Calendar. You're definitely shared on it. :smile: :calendar:

**Comment by joshfinnie** [comment]
oh yeah... I am on that one. Thought we had something NodeDC specific. :-)

**Comment by JuanCaicedo** [comment]
We've got our space if we want to do 2/4 at Fluencia. @joshfinnie want to make an event, or want me to?

**Comment by JuanCaicedo** [comment]
http://www.meetup.com/node-dc/events/228264736/

**Comment by joshfinnie** [comment]
Whoooooo!

**Comment by joshfinnie** [comment]
:bell: :no_bell: :bell:

**Comment by JuanCaicedo** [comment]
:+1: Let's schedule the next one!
