### ISSUE TITLE
NodeSchool mentorship

### ISSUE THREAD

**Issue by danpaz** [NodeDC/organizers#45]
:loudspeaker: :loudspeaker: :loudspeaker: I wanted to get some discussion going around:
- how to get more mentors on board
- what it means to be a mentor with NodeSchoolDC
- how many mentors we need

Afaik the only mentors right now are the organizers, and there is no process for a member wanting to become a mentor to do so. Mentors are key to sustaining and growing the community we've built with NodeSchoolDC. 

How I think we should recruit mentors:
- Announce at events that we're looking for mentors, have them speak to one of the organizers about it
- Approach members we see attend the events repeatedly -- they're already primed for mentorship
- Have clear roles/responsibilities drawn up so prospective mentors know what to expect

What I think mentors should be responsible for:
- Introducing themselves as someone to ask for help during nodeschool events
- Committing to attending approx. every other nodeschool event, or as many events as possible 
- Completing a certain number of workshoppers, minimum probably learnyounode, javascripting, etc. so they can answer questions about them
- Maybe helping out with spreading the word about future events?
- In the future we could formalize mentorship further by pairing new members with a mentor to work with them even outside of nodeschool events.

How many mentors I think we need:
- As many as possible!
- I'd love to shoot for ~10 at first, that's about 1 mentor to every 3-4 members at a typical event

Related:
- #41
- NodeSchool [guidance](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) on [mentorship](http://nodeschool.io/mentor-at-event.html)

Please share your thoughts, thanks all!

**Comment by JuanCaicedo** [comment]
Random thought, but do you think the RSVP medium has an effect on this? Both Toronto and Baltimore use TiTo instead of meetup, which lets you sign up specifically as a mentor

**Comment by danpaz** [comment]
That's a good thought, I bet that does have some effect. Meetup lets you ask members a question when they RSVP, we could try using that to ask if they want to attend as a mentor.

**Comment by danpaz** [comment]
https://github.com/nodeschool/oakland/issues/24 this approach could work :smile_cat:

**Comment by danmactough** [comment]
> nodeschool/oakland#24 this approach could work

:100:
