### ISSUE TITLE
Oct 25 Joint NodeTogether/NodeSchool

### ISSUE THREAD

**Issue by danmactough** [NodeDC/organizers#47]
Logistics & Coordination

**Comment by robbiethegeek** [comment]
I would like to make sure that we have the event posted ASAP since it is now 8 days away.  Also we should mention it on Saturday @ the NodeSchoolDC event.

**Comment by danmactough** [comment]
Here's the draft meetup announcement:

---

Q. What is NodeSchool ? 

A. Open source workshops that teach web software skills. 

There are 6 core NodeSchool workshops that teach the basic concepts of JavaScript, Node.js, npm, git... (javascripting, git-it, Scope Chains & Closures, learnyounode, How to npm and stream-adventure) and electives, these are to learn popular libraries or styles of writing Node.js.  You will be paired off with another attendee at your level and together you will go through one of the NodeSchool workshops with support from your friendly, neighbohood mentors.

Now that you know that, come and learn some Node.js flavored development! No previous experience required.  You will be paired off with someone at your skill level that is working on the same workshop you are. There will be mentors available to assist you if you need a hand completing a specific exercise within the 6 core workshops, or to answer your other node.js questions. 

Prerequisites: 

• bringing a laptop  
• Install Node.js on that laptop (if you are having issues installing please tell a mentor when you arrive, so we can get you working).

In general, we take photos of the entire group at these events and post them to Instagram / Twitter.  If this is something that you have an issue with, please chat with the organizers (most likely Robbie - he does most of the posting) and we will be happy to try to accommodate.

**Comment by danmactough** [comment]
NodeTogether info:

---

Our partner organization, NodeTogether, will be teaching a free workshop the evening prior, which is aimed to make Node a more diverse space by bringing people of underrepresented groups together to get started in learning Node.js(beginner course). We're looking for applicants as well as friendly Node.js mentors! Please let me know if you have any questions.

**Comment by hackygolucky** [comment]
Yup yup! We prob should make sure that folks notice they should apply to NodeTogether(as much as possible) so that we can make sure the folks getting in on that side of the event are the ones who most need it(new programmers, very new to Node from other languages, etc). I'll make sure that I point everyone to the NodeSchool class as another great option!

We are also looking for mentors if y'all just happen to have too many on the NodeSchool side of the house :P

**Comment by danmactough** [comment]
Ok how about this:

---

Title:

Tour De Code 2016 - NodeTogether & NodeSchoolDC

Description:

NodeDC and The Node Foundation are co-hosting NodeTogether & NodeSchoolDC!

Q. What is NodeTogether? http://nodetogether.org/

A. A free workshop aimed to make Node a more diverse space by bringing people of underrepresented groups together to get started in learning Node.js (beginner course).

Q. What is NodeSchool? http://nodeschool.io/

A. Open source workshops that teach web software skills.

Q. How are NodeTogether and NodeSchool different?

A. NodeTogether is designed for the absolute beginner. NodeSchool assumes some familiarity with programming concepts (but not much).

More about the NodeTogether workshop:

The ideal student for a NodeTogether event is a new or junior developer who is interested in getting started with Node.js. We don't expect you to have any programming experience and will be spending a lot of time getting a development environment set up.

Additionally, we are particularly interested in people from underrepresented groups, including but not limited to, women, people of color, people with mental and/or physical disabilities, LGBTQ, and non-binary people.

We're looking for [applicants](http://www.nodetogether.org/#apply) as well as friendly Node.js [mentors](http://www.nodetogether.org/#help)! Please let us know if you have any questions.

More about NodeSchoolDC:

There are 6 core NodeSchool workshops that teach the basic concepts of JavaScript, Node.js, npm, git... (javascripting, git-it, Scope Chains & Closures, learnyounode, How to npm and stream-adventure) and electives. These are to learn popular libraries or styles of writing Node.js. You will be paired off with another attendee at your level, and together you will go through one of the NodeSchool workshops with support from your friendly, neighbohood mentors. Mentors will be there to assist you if you need a hand completing a specific exercise within the 6 core workshops, or to answer your other node.js questions.

Now that you know that, come and learn some Node.js flavored development! No previous experience required.

Prerequisites:

• Bring a laptop with Windows, OSX, or Linux installed

• For NodeSchool, try to install Node.js on that laptop (if you are having issues installing please tell a mentor when you arrive, so we can get you working).

In general, we take photos of the entire group at these events and post them to Instagram / Twitter. If this is something that you have an issue with, please chat with the organizers (most likely Robbie - he does most of the posting) and we will be happy to try to accommodate.

**Comment by robbiethegeek** [comment]
LGTM 👍 :shipit:  :) Let's post this, and we should talk about if there is a shared slide deck to introduce the mentors on both sides.  I know for a fact that I have been recruiting a lot of the members of the DC FemTech communities to mentor on the NodeSchool DC side of the house and would love to get folks some recognition for stepping up :)

**Comment by danmactough** [comment]
Almost there, @robbiethegeek -- @hackygolucky We always thank our sponsor in our announcements, but I'm not sure (looking at the previous NodeTogether events) if npm is sponsoring f&b. If not, we have sponsor && from NodeSource.

---

We'll have a great space courtesy of Social Tables and food and drink courtesy of NodeSource.

Also, please help us out and check out our sponsor Hired.com. ← When you use that link and sign up for Hired, NodeDC will get a referral fee!

Members of the NodeDC community are expected to adhere to our Code of Conduct.

**Comment by jakerella** [comment]
Yaaaay! Where did we land on venue?

**Comment by danmactough** [comment]
Social Tables

**Comment by danmactough** [comment]
Alright. I'm going to make this live. Please let me know if we need to update it, Tracy.

**Comment by danmactough** [comment]
this happened 🎉
