### ISSUE TITLE
StrongLoop Workshop on LoopBack 5/18

### ISSUE THREAD

**Issue by adunkman** [NodeDC/organizers#5]
We’re doing this! @jakerella is leading a workshop on May 7th: http://www.meetup.com/node-dc/events/221880003/. @danmactough is (graciously) leading this one.

**Comment by adunkman** [comment]
Scheduled tweets for: 
- Monday, April 20 at 9:15am
- Thursday, April 23 at 10:30am
- Thursday, April 30 at 3:00pm
- Thursday, May 7 at 10:00am (including a reminder about 6:30pm start time).

Didn’t do as many “In two days!” “Tomorrow!” tweets on this one since I’m expecting to have a pretty high RSVP count, and don’t want to taunt people with something they can’t attend. We can always add those later if need be!

**Comment by adunkman** [comment]
We’ve got a strong list of RSVPs so far, at 80. This is pushing the capacity of UberOffices Dupont, if everyone shows — and we still have a long time to go before RSVPs close. 

We’re averaging about 40-50% turnout on our last few meetups, but not sure if we should expect higher or lower turnout considering this is a workshop. I’d anticipate higher than average. 

We have an offer on the table for another space which might be larger, I’ll do some follow-up on that right now and report back.

**Comment by jakerella** [comment]
Hi folks! Didn't know about this repo, but glad to see it. Here's my $0.02 from past workshops and meetups generally: yes, expect a slightly lower attrition rate (higher turnout) since it's a workshop, but not much more. I'd say 50-60% attendance. I think I asked Dan to cap the RSVPs at 80, so we should have a waitlist started on Meetup.com for it (if @danmactough set that switch).

As for a new venue, I'm all for it (I had emailed Dan about this a week ago to brainstorm ideas). Honestly, if we can find a 100+ person space I think we can fill it. StrongLoop (and I) will do some social media outreach for it. I know of a few people coming in from Baltimore (or between DC and B-mo). My boss has informed me that if we can go bigger on this meetup StrongLoop can kick in up to $500 for venue costs.

On the schedule: I'll try to show up about 5:30 at whatever venue it is to help set up in case we need to move tables around. Food and beverages should arrive about that time as well so that they are set up for people arriving around 6pm. We'll want to get started pretty close to 6:30 as the workshop really is 3 hours (and tight at that). I'll also have a bunch of swag (shirts, stickers, etc) to set out, but won't be enough for everyone, so closer to the event I'll advise people to show up "on time". :)

Let me know if I can help in any other way!

**Comment by mcwhittemore** [comment]
What is the max of the Loft? We might want to reach out to ISL too. I talked with @jray recently about using their space.

**Comment by danmactough** [comment]
We've got space at iSL.

**Comment by adunkman** [comment]
Great! I’ll contact Jazmin at UberOffices Dupont and cancel our reservation for 5/7.

**Comment by recursivefunk** [comment]
Looking forward to hosting you guys!

**Comment by mcwhittemore** [comment]
Do we need to update the location on Meetup?

**Comment by danmactough** [comment]
@mcwhittemore I had a couple of follow-up questions for Rashel at iSL to make sure they're okay with what we need. As soon as I hear back from her, I'll update the meetup announcement.

**Comment by mcwhittemore** [comment]
Oh man, this is going to be so close to home I have to show up :)

**Comment by danmactough** [comment]
> Oh man, this is going to be so close to home I have to show up :)

Too bad you're wait-listed. :trollface:

**Comment by mcwhittemore** [comment]
But bigger space...

**Comment by danmactough** [comment]
Your logic is no defense for my trolling

**Comment by mcwhittemore** [comment]
:( there is no naive thing I can say in response to that in encourage more trolling

**Comment by danmactough** [comment]
You're all like
![miserable-cat](https://cloud.githubusercontent.com/assets/357481/7245557/2b7e5d6a-e7bb-11e4-871c-ae65c622c9e7.jpg)

And I'm all like
![party-kid](https://cloud.githubusercontent.com/assets/357481/7245560/36f4663a-e7bb-11e4-9b51-1c3e40cb2b63.gif)

**Comment by mcwhittemore** [comment]
I think I'm more like:

> Why does it take so long to install mysql...

**Comment by danmactough** [comment]
#first-world-problems

**Comment by jakerella** [comment]
@danmactough Any update from the new venue?

**Comment by danmactough** [comment]
@jakerella Just finished an email conversation, and we are all set. I've updated the meetup announcement and increased the RSVP limit to 100.

**Comment by jakerella** [comment]
How many can the venue hold? At a 100 RSVP limit I'd expect 50-60 to attend.

**Comment by danmactough** [comment]
@jakerella They've got enough tables and chairs for about 80 plus additional chairs. I'm sending you additional details off-list.

Nearer to the event date, we'll assess the size of the waitlist, ask people to update their RSVPs, and hopefully add a bunch more people from the waitlist (if any).

**Comment by jakerella** [comment]
Okay, I trust you to know your group. :)

At other locations we usually just assume 40-50% attrition and set the RSVP cap accordingly. Should we post a comment that tells people to join the waitlist as we'll be evaluating it closer to the event?

**Comment by danmactough** [comment]
> Should we post a comment that tells people to join the waitlist as we'll be evaluating it closer to the event?

I think what we've got is ok.

**Comment by jakerella** [comment]
:+1:

**Comment by danmactough** [comment]
FYI @JuanCaicedo @danpaz, we had to reschedule the upcoming workshop from 5/7 to Monday 5/18.

**Comment by adunkman** [comment]
Whew, good thing @jakerella [tweeted](https://twitter.com/jakerella/status/593071641221066752) about this, because I forgot to update the scheduled tweets with the new date! Doing so now.

**Comment by adunkman** [comment]
Updated: 

![image](https://cloud.githubusercontent.com/assets/14930/7373201/1697ba48-ed99-11e4-8a72-93e4d4ca9fb6.png)

**Comment by danpaz** [comment]
@danmactough Thanks for the heads up! We're going to move our May talk back a week to the 28th to avoid having two events in the same week. 

Tweets look good!

**Comment by danmactough** [comment]
Ok. Sorry about that, @danpaz.

**Comment by danpaz** [comment]
No problem at all!

**Comment by danmactough** [comment]
So... anybody have a lead on space for 80 ppl tonight...

**Comment by jonathana** [comment]
Working on one....

**Comment by jakerella** [comment]
Fluencia rocks! Literally 8 hour notice... I'm glad you weren't booked up tonight!

**Comment by danmactough** [comment]
> Fluencia rocks!

And @jonathana rocks! Thanks for helping with that, Jonathan!

**Comment by jkeam** [comment]
:clap:

**Comment by JuanCaicedo** [comment]
We're excited!

**Comment by adunkman** [comment]
It’s happening!!!!

![me when i try to jump and tap my heels together](https://dl.dropboxusercontent.com/u/424495/GIFs/wahooo-ouch.gif)

**Comment by danmactough** [comment]
Easy peasy!
![train_wreck_at_montparnasse_1895](https://cloud.githubusercontent.com/assets/357481/7692704/095df67e-fd95-11e4-91fb-ac87550d4a53.png)

**Comment by jkeam** [comment]
lol that pic is great

**Comment by adunkman** [comment]
> lol that pic is great

+1, would silently laugh again!

**Comment by jonathana** [comment]
Is that the pic of iSL's construction project?

J
