### ISSUE TITLE
Booking space for next round of presentations and Node Nights

### ISSUE THREAD

**Issue by adunkman** [NodeDC/organizers#7]
Our 5/7 event (#5) is our last scheduled event, so it’s time to start booking dates and arranging speakers for them (we’re currently figuring out our speakers in #3).

UberOffices Dupont has been great to deal with from an organizers perspective (a.k.a. my perspective) so I’d like to continue using their space. I think it’s nice to keep our events in the same location.

I’ve just emailed our contact at UberOffices to [cancel our space for 5/7](https://github.com/NodeDC/organizers/issues/5#issuecomment-94537636), and have asked if they’d be willing to host another round of our events.

> Happy Monday! Hope you had a nice weekend. :) 
> 
> Our May 7th workshop is more popular than we’re expecting, and the presenter was concerned about not having enough space at UberOffices Dupont. 
> 
> iStrategyLabs was kind enough to offer their larger space — so we won’t be needing UberOffices on 5/7.
> 
> ——————————————
> 
> On the subject of reservations, we’re getting ready to start our next run of presentations. UberOffices has been a great space for Node.DC, and we’d love to continue having our meetups in your space — are you open to that? Is there anything we can do to help out? 
> 
> Thanks,
> Andrew

**Comment by danmactough** [comment]
:+1: for UberOffices. They're really accommodating. Only complaint is the front-door situation, but otherwise, it's a great venue for us.

**Comment by jonathana** [comment]
As you can guess (since I'm a tenant, and I originally arranged with them
to use Dupont), I'm a fan of staying at Uberoffices.

**Comment by adunkman** [comment]
Wahoo! It’s settled, we’ll stay with UberOffices if they’ll have us (I’m pretty sure they will!).

**Comment by jonathana** [comment]
I can talk to the owners if you have issues, or want the community managers
predisposed to be helpful :-)

**Comment by adunkman** [comment]
:heart: :heart: :heart:
