### ISSUE TITLE
Nodebots Day

### ISSUE THREAD

**Issue by mcwhittemore** [NodeDC/organizers#8]
@danpaz @cshenoy @voodootikigod @JuanCaicedo 

We should get together soon and start talking about how to make Nodebots Day 2015 amazing!

**Comment by JuanCaicedo** [comment]
We're all really excited at Fluencia! We can definitely host again.

@mcwhittemore Are you coming to Nova Node tonight? All the rest of us are, maybe we can chat a bit then.

**Comment by adunkman** [comment]
I think @rektide would be interested, too!

**Comment by mcwhittemore** [comment]
@JuanCaicedo my Mom is in town so I wasn't able to come tonight. Did you all talk about it at all?

**Comment by danpaz** [comment]
@mcwhittemore we talked about it briefly and decided to talk more about it in this issue, so here goes :)

Things I think worked well last year:
- Spreading the word by asking other JS meetups to announce the event.
- Selling kits at a slightly discounted price for folks without hardware.
- Short intro to johnnyfive at the beginning. 
- People show and telling their projects throughout the day.

Things I think we should try this year:
- If someone has a bigger project they're working on maybe they can ask for other attendees to help out?
- We talked about having some kind of competition at the end of the day. Can we do it? should we?
- I think we had about 30 attendees last year. The space can certainly accommodate more, if we want the event to be bigger.

**Comment by JuanCaicedo** [comment]
(I wasn't there last year, so I don't really know how it goes down)

How similar are the things people work on? My thought is that if everyone has pretty varied interests, maybe some time of competition would instead bias them towards trying similar things, and I would assume we want to encourage all the variety and creativity we can. However, if people work on pretty similar things, then a competition could be pretty feasible and fun! It could also give more direction to people that don't know what to work on.

Let's go as big as we can!

**Comment by mcwhittemore** [comment]
I think a contest could be great. We can use it to help give people focus and also to help create teams. If we want to go that way, we should have the kit we sell be about the goal.

**Comment by adunkman** [comment]
I’m not poo-pooing this (I’d love to see it happen, and I’d most likely attend!) but I have to be honest about what I can realistically contribute in my free time. I’m not able to contribute to this event more than the normal Node DC things (tweeting about it, making sure things are settled on Meetup, trying to introduce you to people you’ll want to know).

Anybody (on this thread currently or not) want to take this on as their baby and make it happen?

**Comment by JuanCaicedo** [comment]
Not to worry Andrew, I think we're taking the lead on it through NovaNode since Fluencia is going to set up buying/providing hardware.

**Comment by adunkman** [comment]
Yussssssss!

![image](https://cloud.githubusercontent.com/assets/14930/7706378/1db2ce3c-fe18-11e4-89bd-3f34030df2ae.png)

**Comment by mcwhittemore** [comment]
@rickyvetter what was the name of the bot kit you used at JSConf, that would be a good starter kit for people.

It looks like I'll most likely be out of town during this weekend :(

**Comment by rickyvetter** [comment]
The bot kit we used was called the [Pee Wee Runt Rover](https://www.servocity.com/html/peewee_runt_rovertm__637158_.html). You can see everything we used if you follow the [slides from the event](https://dl.dropboxusercontent.com/u/3531958/jsconf-2015/index.html). The only thing I remember that wasn't in the robot kit or the [ARDX starter kit](http://www.adafruit.com/products/170) was the Pololu DRV8835 Shield.

**Comment by mcwhittemore** [comment]
So, my plans for this weekend just fell through, so I think I'll be in town.

Who is going to be on the nodebots day call on Wednesday?

**Comment by danpaz** [comment]
I'll be on the call!

**Comment by danpaz** [comment]
My notes from the meeting:

Nodebots Day

Meeting 1 notes
- Leading up to the event:
  - Set up a simple website (even just a readme in github).
  - Signup page (tito, eventbrite).
  - Should I charge? Up to you, Chris charges $ 5-10, to ensure people come. 
  - Stickers!
  - Sponsorships - ask in the signup form. 
- Bring extra supplies: 
  - If you don't have any, buy (www.seeedstudio.com) or borrow. 
  - Buy: ARDX kit ($60), Sparkfun inventors kit ($100), Nodecopter kits from any Apple store, Sumobot (great for competitions), SparkCore (now called particle). 
  - Provide an option to bring your hardware home as part of the ticket.
  - Option to pay half and pair up.
- Venue:
  - Ask sponsors.  
  - Look for an air conditioned place.
- Day of:
  - Spend first 5-10 minutes outlining the day. Walk-through instructional flash-an-LED intro.
  - Expect to have to help people install node. (v0.10 is the safest bet).
  - `npm install johnny-five` installs serialport, may have some issues with Windows - ping Chris if so.
- Be creative! Check out johnny-five examples.
- 1-1.5h at the end to share what people built.
- Make sure participants know about the code of conduct.

Different this year:
- Chris has a posse from jsconf working in shifts to assist.
- Use the slack channel to contact these people for questions.
- Gitter nodebotsday https://gitter.im/nodebots/nodebotsday.
- Possibly coupons for kits, possibly tshirts.

**Comment by mcwhittemore** [comment]
Thanks for the notes @danpaz! 

Do we want a nodebotsday repo here so we can build an about page?

**Comment by danpaz** [comment]
Chris and others suggested adding a PR to the nodebots readme so I went ahead and did that https://github.com/nodebots/nodebotsday/pull/153. I like the idea of building our own about page too!

@mcwhittemore do you have last year's ti.to account and can we reuse that for this year? 

I'll be out of town for the next month, and I will be back in time for the event itself, but I will try to help out from abroad as best I can! :smile: :airplane:

**Comment by adunkman** [comment]
FYI, [The Internet, er LAN of Things](http://www.meetup.com/node-dc/events/223661595/) is soon-to-be announced (the week before Nodebots), hoping it spurs/reinvigorates some Nodebotsy interest!

We had another nodebotsy talk too, but the speaker wasn’t able to make the date.

**Comment by JuanCaicedo** [comment]
@mcwhittemore I just wanted to ping you again about whether we have a ti.to account or if we should make one. 

As for another repo, I'd lean towards just using the one on Nodebots, since Dan's [PR is merged](https://github.com/nodebots/nodebotsday#washington-dc-usa). We can have all the details there and also we'll put up an event linking to there from NovaNode, maybe NodeDC too. I can add the sign up page as soon as we have some details for it.

**Comment by robbiethegeek** [comment]
Hey folks is the nodebots event happening on 7/25/15?

**Comment by JuanCaicedo** [comment]
We're still planning on hosting at Fluencia. I'm going to go ahead and make a new sign up account for it tomorrow and then I'll post the link.

**Comment by JuanCaicedo** [comment]
[Here's](https://ti.to/nova-node/nodebots-dc-2015) our sign up! I'll try to see if we can get a sweet logo like last year.

I'm looking into what hardware to offer for people who are interested in buying some. The [Adafruit](http://www.adafruit.com/products/170) is $85, while the [Pee Wee Runt Rover](https://www.servocity.com/html/peewee_runt_rovertm__637158_.html) that Ricky suggested is $16. I have no idea about what they're each like and how much people who are interested in the event mind spending.

**Comment by danpaz** [comment]
It's happening!
